#!/bin/bash
echo "Enter the value for num1"
read num1
echo "Enter the value for num2"
read num2
sum=`expr $num1 + $num2`
sub=`expr $num1 - $num2`
prod=`expr $num1 \* $num2`
div=`expr $num1 / $num2`
echo="the sum of $num1 and $num2 is $sum"
echo="the sum of $num1 and $num2 is $sub"
echo="the sum of $num1 and $num2 is $mul"
echo="the sum of $num1 and $num2 is $div"
 
